### ISSUE TITLE
Strange factorization results

### ISSUE THREAD

**Issue by ghost** [Yaffle/QuadraticSieveFactorization#2]
When I factorize something like 10<sup>30</sup>, output is 2<sup>30</sup> &#215; 2<sup>30</sup> &#215; _25_ instead of 2<sup>30</sup> &#215; 2<sup>30</sup> 🤔

**Comment by Yaffle** [comment]
@rattleSSnake , thanks, I have fixed the demo, it should work better now

**Comment by rattleSSnake** [comment]
Also please why is `quadraticSeive(125)` returning 25 instead of 5 ?
It works perfectly for all other numbers but for 125 it doesn't return the smallest divisor. Here is my integration using generators:
```js
while (n !== 1n) {
    const f = BigInt(millerRabinPrimalityTest(n) ? n : quadraticSeive(n));
    console.log("From this number ", n, "Quadratic seive returns ", BigInt(quadraticSeive(n)));
    yield { divisors: f };
    n /= f;
  }
```
Thanks because I plan to use your algo on my project and I'd like to understand some weird behaviours.

<img width="263" alt="example" src="https://user-images.githubusercontent.com/89637856/187068845-e51f66ca-2952-48d2-a144-0f6f758a4ea6.png">

**Comment by rattleSSnake** [comment]
Also please why is `quadraticSeive(125)` returning 25 instead of 5 ?
It works perfectly for all other numbers but for 125 it doesn't return the smallest divisor. Here is my integration using generators:
```js
while (n !== 1n) {
  const f = BigInt(millerRabinPrimalityTest(n) ? n : quadraticSeive(n));
  console.log("From this number ", n, "Quadratic seive returns ", quadraticSeive(n));
  yield { divisors: f };
  n /= f;
}
```
I noticed (see screenshot) that the only times qs returns a bigint is when number is 125, maybe there is some problem with your code ?

<img width="257" alt="image" src="https://user-images.githubusercontent.com/89637856/187069250-bad96968-f522-4aa5-b1a2-86ec16d70ee4.png">

Thank so much because I plan to use your algo on my project

**Comment by ghost** [comment]
@Yaffle also please why is `quadraticSeive(125)` returning 25 instead of 5 ?
Factorization works perfectly but for 125 it doesn't return the smallest divisor. Here is my integration using generators:
```js
while (n !== 1n) {
  const f = BigInt(millerRabinPrimalityTest(n) ? n : quadraticSeive(n));
  console.log("From this number ", n, "Quadratic seive returns ", quadraticSeive(n));
  yield { divisors: f };
  n /= f;
}
```
Also, I noticed (see screenshot) that the only times qs returns a bigint is when number is 125, maybe there is some problem with your code ? Also I believe that the number 125 is not necessarly the problem because the same things happens with other numbers at a certain point during factorization.

<img width="257" alt="image" src="https://user-images.githubusercontent.com/89637856/187069250-bad96968-f522-4aa5-b1a2-86ec16d70ee4.png">

Thank so much because I plan to use your algo on my project

**Comment by Yaffle** [comment]
@rattleSSnake it returns some factor, not necessary prime, so this is expected

**Comment by Yaffle** [comment]
@rattleSSnake , btw, the Quadratic Sieve algorithm is not efficient when a number has s small factor, so for real usage you should try at first to run few iterations of "Pollard's rho algorithm" or something else, then switch to this one.

**Comment by ghost** [comment]
> @rattleSSnake it returns some factor, not necessary prime, so this is expected

Ok... but why is it returning a bigint instead of a number like the others ? 

Every time the factor is not prime it returns a bigint 🤔

**Comment by Yaffle** [comment]
@rattleSSnake , there is branch in the code which returns numbers, I have changed it to return bigints

**Comment by Yaffle** [comment]
@rattleSSnake , btw, you should not call it for prime numbers, it will work infinitely for huge primes

**Comment by Yaffle** [comment]
it also hangs for perfect powers, seems

reopening the issue to document the usage

**Comment by Yaffle** [comment]
I have added a section "Usage Notes" - https://github.com/Yaffle/QuadraticSieveFactorization/blob/main/README.md#usage-notes
